// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class ciudades
{
    public int id_ciudad { get; set; }

    public string ciudad { get; set; }

    public virtual ICollection<direciones> direciones { get; set; } = new List<direciones>();
}