// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class cliente
{
    public int id_cliente { get; set; }

    public int? id_tipo_cliente { get; set; }

    public string nombres { get; set; }

    public string apellidos { get; set; }

    public string telefono { get; set; }

    public string correo { get; set; }

    public virtual ICollection<direciones> direciones { get; set; } = new List<direciones>();

    public virtual tipo_cliente id_tipo_clienteNavigation { get; set; }

    public virtual ICollection<pedido> pedido { get; set; } = new List<pedido>();
}