// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class detalle_pedido
{
    public int id_detalle_pedido { get; set; }

    public int id_pedido { get; set; }

    public int id_producto { get; set; }

    public int cantidad { get; set; }

    public decimal precio_unitario { get; set; }

    public decimal subtotal { get; set; }

    public virtual pedido id_pedidoNavigation { get; set; }

    public virtual producto id_productoNavigation { get; set; }
}