// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class direciones
{
    public int id_direccion { get; set; }

    public string calle_principal { get; set; }

    public string calle_secundaria { get; set; }

    public string numero { get; set; }

    public string referencias { get; set; }

    public int? id_cliente { get; set; }

    public int? id_provincia { get; set; }

    public int? id_ciudad { get; set; }

    public virtual ciudades id_ciudadNavigation { get; set; }

    public virtual cliente id_clienteNavigation { get; set; }

    public virtual provincias id_provinciaNavigation { get; set; }
}