// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class estado_ruta
{
    public int id_estado_ruta { get; set; }

    public string estado_ruta1 { get; set; }

    public virtual ICollection<ruta> ruta { get; set; } = new List<ruta>();
}