// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class estado_pedido
{
    public int id_estado_pedido { get; set; }

    public string estado_pedido1 { get; set; }

    public virtual ICollection<pedido> pedido { get; set; } = new List<pedido>();
}