// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class pedido
{
    public int id_pedido { get; set; }

    public int? id_estado_pedido { get; set; }

    public int? id_cliente { get; set; }

    public DateOnly? fecha_pedido { get; set; }

    public DateOnly? fecha_entrega { get; set; }

    public int? id_ruta { get; set; }

    public virtual ICollection<detalle_pedido> detalle_pedido { get; set; } = new List<detalle_pedido>();

    public virtual cliente id_clienteNavigation { get; set; }

    public virtual estado_pedido id_estado_pedidoNavigation { get; set; }

    public virtual ruta id_rutaNavigation { get; set; }
}