// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class permisos
{
    public int id_permiso { get; set; }

    public string permiso { get; set; }

    public virtual ICollection<roles> id_rol { get; set; } = new List<roles>();
}