// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class precio_producto_historico
{
    public int id_precio_producto_historico { get; set; }

    public int? id_precio_producto { get; set; }

    public DateOnly? fecha_inicio { get; set; }

    public DateOnly? fecha_fin { get; set; }

    public string usuaio_actualiza { get; set; }

    public virtual precio_producto id_precio_productoNavigation { get; set; }
}