// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class producto
{
    public int id_producto { get; set; }

    public string nombre_producto { get; set; }

    public string descripcion { get; set; }

    public int stock { get; set; }

    public virtual ICollection<detalle_pedido> detalle_pedido { get; set; } = new List<detalle_pedido>();

    public virtual ICollection<precio_producto> precio_producto { get; set; } = new List<precio_producto>();
}