// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class roles
{
    public int id_rol { get; set; }

    public string rol { get; set; }

    public virtual ICollection<ruta> ruta { get; set; } = new List<ruta>();

    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();

    public virtual ICollection<permisos> id_permiso { get; set; } = new List<permisos>();
}