// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class ruta
{
    public int id_ruta { get; set; }

    public int? id_estado_ruta { get; set; }

    public int? id_rol { get; set; }

    public DateOnly fecha_inicio { get; set; }

    public DateOnly? fecha_fin { get; set; }

    public virtual estado_ruta id_estado_rutaNavigation { get; set; }

    public virtual roles id_rolNavigation { get; set; }

    public virtual ICollection<pedido> pedido { get; set; } = new List<pedido>();
}