// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class usuario
{
    public int id_usuario { get; set; }

    public int? id_rol { get; set; }

    public string nombres_usuario { get; set; }

    public string apellidos_usuario { get; set; }

    public string correo { get; set; }

    public string contrasena { get; set; }

    public virtual roles id_rolNavigation { get; set; }
}